stages:
  - test
  - deploy

test:
  image: node:16
  stage: test
  before_script:
    - npm i
  script:
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

deploy_registry:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE || true
  script:
    - docker build --pull
        --cache-from $CI_REGISTRY_IMAGE
        --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA
        --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
