language: node_js
node_js:
  - 16
cache:
  directories:
    - $HOME/.npm
    - $(npm config get prefix)/lib/node_modules
install:
  - npm ci
script:
  - npm test
branches:
  only:
    - master
    - /^feature-.*/
after_success:
  - npm i codecov -g && codecov
